name: Auto-sync with GitHub

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes
        run: |
          # Pull only if there are changes to pull
          git pull origin main || echo "No changes to pull"

      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes if any
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "Auto-sync: Update from Replit [skip ci]"
          git push origin main
